/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamMember5RouteImport } from './routes/team/member-5'
import { Route as TeamMember4RouteImport } from './routes/team/member-4'
import { Route as TeamMaryGloriaAwinjaRouteImport } from './routes/team/mary-gloria-awinja'
import { Route as TeamDrMaryKeahOtienoRouteImport } from './routes/team/dr-mary-keah-otieno'
import { Route as TeamDrBettyOgangeRouteImport } from './routes/team/dr-betty-ogange'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as ApiSendTrainingRouteImport } from './routes/api.send-training'
import { Route as ApiSendConsultationRouteImport } from './routes/api.send-consultation'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMember5Route = TeamMember5RouteImport.update({
  id: '/team/member-5',
  path: '/team/member-5',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMember4Route = TeamMember4RouteImport.update({
  id: '/team/member-4',
  path: '/team/member-4',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMaryGloriaAwinjaRoute = TeamMaryGloriaAwinjaRouteImport.update({
  id: '/team/mary-gloria-awinja',
  path: '/team/mary-gloria-awinja',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamDrMaryKeahOtienoRoute = TeamDrMaryKeahOtienoRouteImport.update({
  id: '/team/dr-mary-keah-otieno',
  path: '/team/dr-mary-keah-otieno',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamDrBettyOgangeRoute = TeamDrBettyOgangeRouteImport.update({
  id: '/team/dr-betty-ogange',
  path: '/team/dr-betty-ogange',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const ApiSendTrainingRoute = ApiSendTrainingRouteImport.update({
  id: '/api/send-training',
  path: '/api/send-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendConsultationRoute = ApiSendConsultationRouteImport.update({
  id: '/api/send-consultation',
  path: '/api/send-consultation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/send-consultation': typeof ApiSendConsultationRoute
  '/api/send-training': typeof ApiSendTrainingRoute
  '/events/$id': typeof EventsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/dr-betty-ogange': typeof TeamDrBettyOgangeRoute
  '/team/dr-mary-keah-otieno': typeof TeamDrMaryKeahOtienoRoute
  '/team/mary-gloria-awinja': typeof TeamMaryGloriaAwinjaRoute
  '/team/member-4': typeof TeamMember4Route
  '/team/member-5': typeof TeamMember5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/send-consultation': typeof ApiSendConsultationRoute
  '/api/send-training': typeof ApiSendTrainingRoute
  '/events/$id': typeof EventsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/dr-betty-ogange': typeof TeamDrBettyOgangeRoute
  '/team/dr-mary-keah-otieno': typeof TeamDrMaryKeahOtienoRoute
  '/team/mary-gloria-awinja': typeof TeamMaryGloriaAwinjaRoute
  '/team/member-4': typeof TeamMember4Route
  '/team/member-5': typeof TeamMember5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/send-consultation': typeof ApiSendConsultationRoute
  '/api/send-training': typeof ApiSendTrainingRoute
  '/events/$id': typeof EventsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/dr-betty-ogange': typeof TeamDrBettyOgangeRoute
  '/team/dr-mary-keah-otieno': typeof TeamDrMaryKeahOtienoRoute
  '/team/mary-gloria-awinja': typeof TeamMaryGloriaAwinjaRoute
  '/team/member-4': typeof TeamMember4Route
  '/team/member-5': typeof TeamMember5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/api/send-consultation'
    | '/api/send-training'
    | '/events/$id'
    | '/services/$slug'
    | '/team/dr-betty-ogange'
    | '/team/dr-mary-keah-otieno'
    | '/team/mary-gloria-awinja'
    | '/team/member-4'
    | '/team/member-5'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/api/send-consultation'
    | '/api/send-training'
    | '/events/$id'
    | '/services/$slug'
    | '/team/dr-betty-ogange'
    | '/team/dr-mary-keah-otieno'
    | '/team/mary-gloria-awinja'
    | '/team/member-4'
    | '/team/member-5'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/services'
    | '/sitemap.xml'
    | '/api/send-consultation'
    | '/api/send-training'
    | '/events/$id'
    | '/services/$slug'
    | '/team/dr-betty-ogange'
    | '/team/dr-mary-keah-otieno'
    | '/team/mary-gloria-awinja'
    | '/team/member-4'
    | '/team/member-5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSendConsultationRoute: typeof ApiSendConsultationRoute
  ApiSendTrainingRoute: typeof ApiSendTrainingRoute
  TeamDrBettyOgangeRoute: typeof TeamDrBettyOgangeRoute
  TeamDrMaryKeahOtienoRoute: typeof TeamDrMaryKeahOtienoRoute
  TeamMaryGloriaAwinjaRoute: typeof TeamMaryGloriaAwinjaRoute
  TeamMember4Route: typeof TeamMember4Route
  TeamMember5Route: typeof TeamMember5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/member-5': {
      id: '/team/member-5'
      path: '/team/member-5'
      fullPath: '/team/member-5'
      preLoaderRoute: typeof TeamMember5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/member-4': {
      id: '/team/member-4'
      path: '/team/member-4'
      fullPath: '/team/member-4'
      preLoaderRoute: typeof TeamMember4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/mary-gloria-awinja': {
      id: '/team/mary-gloria-awinja'
      path: '/team/mary-gloria-awinja'
      fullPath: '/team/mary-gloria-awinja'
      preLoaderRoute: typeof TeamMaryGloriaAwinjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/dr-mary-keah-otieno': {
      id: '/team/dr-mary-keah-otieno'
      path: '/team/dr-mary-keah-otieno'
      fullPath: '/team/dr-mary-keah-otieno'
      preLoaderRoute: typeof TeamDrMaryKeahOtienoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/dr-betty-ogange': {
      id: '/team/dr-betty-ogange'
      path: '/team/dr-betty-ogange'
      fullPath: '/team/dr-betty-ogange'
      preLoaderRoute: typeof TeamDrBettyOgangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/api/send-training': {
      id: '/api/send-training'
      path: '/api/send-training'
      fullPath: '/api/send-training'
      preLoaderRoute: typeof ApiSendTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-consultation': {
      id: '/api/send-consultation'
      path: '/api/send-consultation'
      fullPath: '/api/send-consultation'
      preLoaderRoute: typeof ApiSendConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSendConsultationRoute: ApiSendConsultationRoute,
  ApiSendTrainingRoute: ApiSendTrainingRoute,
  TeamDrBettyOgangeRoute: TeamDrBettyOgangeRoute,
  TeamDrMaryKeahOtienoRoute: TeamDrMaryKeahOtienoRoute,
  TeamMaryGloriaAwinjaRoute: TeamMaryGloriaAwinjaRoute,
  TeamMember4Route: TeamMember4Route,
  TeamMember5Route: TeamMember5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
